name: Generate Snake Animation

on:
  # Roda automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  # Permite que você rode manualmente pela aba Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      # Permissão para a Action escrever no repositório
      contents: write

    steps:
      # 1. Pega o código do seu repositório
      - uses: actions/checkout@v3

      # 2. Gera os arquivos da animação
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # 3. Envia os arquivos gerados para a branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
